services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx
    image: nginx
    ports:
      - 9080:80
    volumes:
      - ./html:/usr/share/nginx/html
      - ./conf:/etc/nginx
      - ./log:/var/log/nginx
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
